#!/bin/bash

# Run the command in the scope of the directory
#
# Example:
#
#    safe_run job/12345/workdir ./script.sh --options
#
# After the execution, the log subdirectory contains
#
# log/status

dir=$1
shift

# Simple cd, no jail
{ cd "$dir" && exec "$@"; }

# Use firejail
#firejail --quiet --private="$dir" --seccomp -- "$@"
