#!/bin/bash

# See the README for usage

# Environments variables used trough the script (instead of passing parameters)
#
# * BOX_OUT the output directory (to clean)
#   It contains the various produced files, results and artefact produced by this script.
#   It is set by default to 'out/'
# * BOX_WORK the jailed work directory
#   It is used as the directory where commands are run
#   It is set by default to '$BOX_OUT/work/'
# * BOX_RUN_NAME the name of the current command. (set by `run`)
#   Each executed by `run` need a name and metadata are tracked
# * BOX_RUN_OUT the output basename for the current command metadata. (set by `run`)
#   It is set by default to '$BOX_OUT/tests/$BOX_RUN_NAME'

###############################################################################
# Execution related functions.
#
# Execute some commands in a protected context and log the various results

# This run a single command in a jailed work directory and log its results.
#
# $1 is the unique name of the command (used to read an produce metadata)
# the rest is the command to run.
#
# Example:
#
#     run force_make make -B
#     run my_test1 bin/app argument
#
# The various results of the test will be written in the `out/tests/` directory
run() {
	local name=$1
	export BOX_RUN_NAME=$name
	shift

	# Special dry-up behavior if 'list' or 'status' commands are given.
	if [ "$cmd" = "list-tests" ]; then
		echo "$name"
		return 0
	fi

	if [ "$cmd" = "list" ]; then
		echo "$name: $*"
		return 0
	fi

	mkdir -p $BOX_OUT/tests
	local out=$BOX_OUT/tests/$name
	export BOX_RUN_OUT=$out

	if [ "$cmd" = "status" ]; then
		status "$name"
		return 0
	fi

	# Run the command
	rm $out.* 2> /dev/null || true
	echo "$@" > $out.cmd
	echo "$@" > $out.log
	local code=0
	saferun $BOX_WORK "$@" > $out.out 2> $out.err < /dev/null || code=$?
	echo $code > $out.code
	echo "Command returned $code" >> $out.log

	# Check its result
	local res
	if checkrun && test ! -e $out.fail; then
		res=0
		touch $out.pass
		echo "PASSED" >> $out.log
	else
		res=1
		touch $out.fail
		echo "FAILED" >> $out.log
	fi

	# Display the result
	status

	unset BOX_RUN_NAME
	unset BOX_RUN_OUT

	return $res
}

# Run the command into a specific jail
#
# $1 is the directory to jail
# the rest is the command
#
# TODO: Improve and make configurable
saferun() {
	local dir=$1
	shift

	case "$BOX_JAIL" in
		firejail)
			# Use firejail
			firejail --quiet --private="$dir" -- "$@"
			;;
		none|copy|'')
			# Simple cd, no jail
			( set +e; cd "$dir" && exec "$@"; )
			;;
		*)
			echo >&2 "Error. Unknown jail mode '$BOX_JAIL'"
			return 1
			;;
	esac
}

# Check a run.
#
# This function is called when the result of a run is checked.
# metadata can be read and modified.
checkrun() {
	if [ -e "$bin/checktestcase.sh" ]; then
		echo "bin/checktestcase.sh" >> $out.log
		bin/checktestcase.sh
		return
	fi

	checkrun_core
}

# Default behavior of 'checkrun'
checkrun_core() {
	local name=$BOX_RUN_NAME
	local out=$BOX_RUN_OUT
	local code=`cat $out.code`

	# Check the return code first
	if [ "$code" != "0" ]; then
		echo "Test exited with $code" > $out.fail
		sed 's|^|\t|' $out.err >> $out.fail
		return 1
	fi

	# Check the saved .res file if any
	local res=`echo tests*/$name.res`
	if [ -e "$res" ]; then
		echo "diff -u $res $out.out" >> $out.log
		if ! diff -u $res $out.out > $out.diff; then
			echo "diff -u $res $out.out" > $out.fail
			return 1
		fi
	else
		echo "no res file $res" >> $out.log
	fi

	return 0
}

# Display the status of the test named $1 without running it not.
#
# This just check the content of the out/tests/ directory and display the information to the user.
status() {
	local name=$BOX_RUN_NAME
	local out=$BOX_RUN_OUT

	if [ ! -e $out.cmd ]; then
		echo "[NOT RUN] $name."
	elif [ -e $out.pass ]; then
		echo -n "[PASS] $name. "
		cat $out.pass
		echo ""
	elif [ -e $out.fail ]; then
		echo -n "[FAIL] $name. "
		cat $out.fail
		echo ""
		return 1
	else
		echo "[ABORTED] $name."
	fi
	return 0
}

###############################################################################
# Job related commands
#
# The following functions take care of the whole processing of a source or submission.
# They prepare the tests and the working directory, building, executing testcases, etc.

# Run build && check
work() {
	prepare &&
	build &&
	check
}

# Function called when the engine wants to setup the work directory.
#
# pwd is the root directory of the box.
#
# By default, this just call `prepare_core "$@"`.
# Specific scripts can override it and call `prepare_core` themselves.
prepare() {
	prepare_core "$@"
}

# Default behavior of `prepare`
#
# * Create the `out` directory structure.
# * Copy src
# * Copy tests/*.in
#
# You should override `prepare` instead of this function.
prepare_core() {
	if [ -f tests.txt ]; then
		explode_tests "tests.txt" "tests"
	fi
	if [ -f tests-private.txt ]; then
		explode_tests "tests-private.txt" "tests-private"
	fi

	export BOX_TEST_DIRS=

	if [ -d  tests ]; then
		export BOX_TEST_DIRS="$BOX_TEST_DIRS tests"
	fi

	if [ -z "$BOX_PUBLIC" -a -d tests-private ]; then
		export BOX_TEST_DIRS="$BOX_TEST_DIRS tests-private"
	fi

	# Prepare a working dir
	if [ "$BOX_JAIL" = "none" -a "$BOX_SRC" = "src" ]; then
		export BOX_WORK=.
		return
	fi
	export BOX_WORK=$BOX_OUT/work
	mkdir -p $BOX_WORK

	for testdir in $BOX_TEST_DIRS; do
		mkdir -p $BOX_WORK/$testdir
		cp -ra $testdir/*.in $BOX_WORK/$testdir
	done
	cp -ra src $BOX_WORK/src
	cp -ra $BOX_SRC/* $BOX_WORK/src 2> /dev/null
	cp -ra Makefile $BOX_WORK/
}

# Transform a oto single file testsuite into a BOX directory testsuite
#
# $1 is the file to explode
# $2 is the destination base directory (it must exists).
#
# Each test will be named with a basename of the file to explode + number.
explode_tests() {
	local file=$1
	local dir=$2
	local base=`basename "$file" .txt`

	local n=0
	local cur=
	while read -r line; do
		case "$line" in
			===)
				((n++))
				cur="$dir/$base$n.in"
				> "$cur"
				;;
			---)
				cur="$dir/$base$n.res"
				> "$cur"
				;;
			*)
				echo "$line" >> "$cur"
				;;
		esac
	done < "$file"
}

# Function called when the engine need to build the source, whatever this means
#
# By default, this just call `make` if a Makefile is present in the jailed workdir.
# You might redefine this function but it is often better to implement the build in the Makefile.
build() {
	if test -f $BOX_WORK/Makefile; then
		run "make" "make" "--no-print-directory"
	fi
}

# Function called when the engine need to execute all test-cases.
#
# Each test-case correspond to a file `tests/*.in` where `*` is the name of the test case.
#
# You should not override this function.
check() {
	for testdir in $BOX_TEST_DIRS; do
		for i in $testdir/*.in; do
			local name=$(basename "$i" .in)
			if [ "$cmd" = "list-tests" ]; then
				# Shortcut the list-test
				echo "$name $i"
				continue
			fi
			runtestcase "$name" "$i"
		done
	done
}

# Run a single test.
#
# $1 the name of the test (eg `test1`)
# $2 the .in file (eg `tests/test1.in`)
#
# By default, this call
#
#     run "$1" bin/runtestcase.sh "$2"
#
# You should thus define a 'bin/runtestcase.sh' script that will be executed in the working dir.
#
# Alternatively, you can override this function in 'boxme.local.sh'
# In this case, you must use the `run` command so the execution is jailed and the metadata are collected.
# E.g.
#
#     run "$1" bin/app < "$2"
#     run "$1" java org.app.Main "$2"
#     run "$1" src/hello.sh $(cat "$2")
runtestcase() {
	if [ -e "Makefile" ]; then
		run "$1" make --no-print-directory -s runone IN="$2"
	else
		echo "FatalError: runone not implemented" >&2
		return 1
	fi
}

###############################################################################
# Submission related functions
#
# A submission is represented as a directory "submissions/$name"
#
# Each submission group its own "src/" directory and its own "out/" for results and working directory.

# List all submissions
submissions() {
	if ! test -d submissions/; then
		echo "No submissions"
		return 0
	fi
	for sub in submissions/*; do
		export BOX_SRC=$sub/src
		export BOX_OUT=$sub/out
		local line=`status_line "$sub"`
		echo "$sub: $line"
	done
	return 0
}

# Show a line collecting results for a directory.
status_line() {
	local sub=$1
	if ! test -d "$sub/out"; then
		echo "not run"
		return
	fi
	local runs=`ls "$sub/out/tests/"*.cmd  2>/dev/null | wc -l`
	local pass=`ls "$sub/out/tests/"*.pass 2>/dev/null | wc -l`
	local fail=`ls "$sub/out/tests/"*.fail 2>/dev/null | wc -l`
	echo "$runs run, $pass passed, $fail failed"
}

###############################################################################
# User related functions
#
# Each user submissions is the directory "submissions/$timestamp_$user/".
# If the submission is approuved, then the file "submissions/$timestamp_$users/APPROUVED" exists.
#
# Submissions that does not respect this convention are ignored by the following functions.

# List the last approuved submission for the given user
#
# $1 is the name of the user
user_approuved() {
	for f in submissions/*_"$1"/APPROUVED; do
		test -e "$f" || continue
		local sub=`dirname "$f"`
		local timestamp=`basename "$sub" "_$1"`
		echo "$timestamp $sub"
	done | sort -n | tail -1 | cut -f 2- -d " "
}

# List the users that submitted something
list_users() {
	ls -d submissions/* | sed -n 's|^submissions/[0-9]*_||p' | sort -u
}

###############################################################################
# Various utilities

# echo something on stderr if verbose mode
verb() {
	test "$BOX_VERB" = 0 && return
	echo >&2 "$*"
}

###############################################################################
# Main program

# The main function of the script
#
# This same function is used to manage the default "src/" directory, submissions and users.
#
# * base command just run on a single source
# * submission commands recursively delegate to base commands
# * user commands recursively delegate to submission commands
main() {
	local cmd=$1

	case "$cmd" in
		help|"")
			cat<<-END
			boxme: check submission for programming exercices and competitions.

			Usage: boxme [options] <command> [arguments]

			Options:
			  -C <dir>  change the directory to the given box
			  -p        only use the public information (no effect if no private information is available)
			  -s <dir>  use dir as the source dir ('src/' by default)
			  -o <dir>  use dir as the output dir ('out/ be default)
			  -j <mode> set a jail mode:
			     none      work in the current directory
			     copy      create a work directory and copy files
			     firejail  like copy but use firejail
			  -v        be more verbose

			Commands:
			  help             display this help
			  list             list all testcases
			  status           the status of each testcases
			  tests            execute all testcases
			  sub list         list all the submissions
			  sub <cmd>        execute the command on all the submissions
			  sub <name> <cmd> execute the command on the named submission
			Advanced commands
			  runone <in>      simple wrapper to make runone with an input file
			  saferun <cmd>    run a command in a jail. see saferun()
			  function <cmd>   run a boxme function (very advanced!)
			Plumbing commands (intended to be used by scripts and tools)
			  list-src         list files in the current source directory
			  list-tests       list the name and the optional input file of each testcases
			END
			exit 0
			;;
		list|status|list-tests)
			# TODO filter specific tests?
			:
			;;
		list-src)
			find "$BOX_SRC" -type f -print
			return
			;;
		tests)
			# TODO filter specific tests?
			test -e "$BOX_OUT/work" && rm -r "$BOX_OUT/work"
			test -e "$BOX_OUT/tests" && rm -r "$BOX_OUT/tests"
			work
			return
			;;
		saferun)
			shift
			saferun "$@"
			return
			;;
		runone)
			saferun "$BOX_WORK" make -s runone IN="$2"
			return
			;;
		function)
			shift
			"$@"
			return
			;;
		sub)
			shift
			if [ "$1" = "list" -o -z "$1" ]; then
				submissions
				exit
			fi
			for sub in "submissions/$1"; do
				if [ -d "$sub" ]; then
					shift
					export BOX_SRC=$sub/src
					export BOX_OUT=$sub/out
					if [ -z "$1" ]; then
						status_line "$sub"
					else
						main "$@"
					fi
					return
				fi
			done
			for sub in submissions/*/; do
				echo "# $sub"
				export BOX_SRC=$sub/src
				export BOX_OUT=$sub/out
				main "$@"
			done
			return
			;;
		user)
			shift
			if [ "$1" == "list" -o -z "$1" ]; then
				list_users
				return
			fi
			for user in `list_users`; do
				sub=`user_approuved "$user"`
				sub=`basename "$sub"`
				if [ -z "$sub" ]; then
					echo "# $user: no approuval"
				else
					echo "# $user: $sub"
					main sub "$sub" "$@"
				fi
			done
			return
			;;
		*)
			echo 2>&1 "Unknown command $cmd. Use the command 'help'."
			exit 1
			;;
	esac

	work
}

export BOX_PUBLIC=
export BOX_OUT=out
export BOX_SRC=src
export BOX_JAIL=none
export BOX_VERB=0
export BOX_WORK=.

# Source the local configuration, is any
if [ -f boxme.local.sh ]; then
	. boxme.local.sh
fi

while getopts ":C:ps:o:j:v" opt; do
	case "$opt" in
		C)
			cd "$OPTARG" || exit
			;;
		p)
			export BOX_PUBLIC=yes
			;;
		s)
			export BOX_SRC=$OPTARG
			;;
		o)
			export BOX_OUT=$OPTARG
			;;
		j)
			export BOX_JAIL=$OPTARG
			;;
		v)
			((BOX_VERB += 1))
			export BOX_VERB
			;;
		\?)
			echo >&2 "Invalid option: -$OPTARG"
			;;
		:)
			echo >&2 "Option -$OPTARG requires an argument."
			exit 1
			;;
	esac
done
shift $(($OPTIND - 1))

main "$@"
